# Generated by Django 2.2.2 on 2019-12-08 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_image', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('wallpaper', models.CharField(max_length=300)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Category')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('plyr_score', models.CharField(max_length=40)),
                ('no_of_player', models.IntegerField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_dob', models.DateField()),
                ('user_address', models.CharField(max_length=400, null=True)),
                ('user_gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('is_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_desc', models.CharField(max_length=400)),
                ('rules', models.CharField(max_length=400)),
                ('player_limit', models.IntegerField()),
                ('re_player', models.IntegerField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('reg_open', models.CharField(max_length=4)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users')),
            ],
            options={
                'db_table': 'tournament',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_price', models.IntegerField()),
                ('p_desc', models.CharField(max_length=300)),
                ('in_stock', models.CharField(max_length=10)),
                ('p_image', models.CharField(max_length=400)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('plyr_id', models.AutoField(primary_key=True, serialize=False)),
                ('plyr_name', models.CharField(max_length=30)),
                ('plyr_score', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Tournament')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_status', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('date_paid', models.DateField()),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_desc', models.CharField(max_length=400)),
                ('f_date', models.DateField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
