# Generated by Django 2.2.2 on 2019-12-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='plyr_score',
            new_name='team_score',
        ),
    ]
