# Generated by Django 2.2.2 on 2019-12-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20191208_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
