# Generated by Django 2.2.2 on 2019-12-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20191208_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Category'),
        ),
    ]
