# Generated by Django 2.2.2 on 2019-12-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20191208_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='t_id',
            field=models.ForeignKey(db_column='t_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users'),
        ),
    ]
