# Generated by Django 2.2.2 on 2019-12-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_auto_20191208_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users'),
        ),
        migrations.AlterField(
            model_name='game',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='o_id',
            field=models.ForeignKey(db_column='o_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Order'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.Users'),
        ),
    ]
