# Generated by Django 2.2.2 on 2019-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0008_auto_20191214_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=300),
        ),
    ]
